name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle 8.2
        run: |
          wget https://services.gradle.org/distributions/gradle-8.2-bin.zip
          unzip gradle-8.2-bin.zip
          export PATH=$PWD/gradle-8.2/bin:$PATH
          gradle -v

      - name: Build APK
        run: |
          export PATH=$PWD/gradle-8.2/bin:$PATH
          gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: JoyToKeyAPK
          path: app/build/outputs/apk/debug/app-debug.apk
